### ISSUE TITLE
error if protocol is not present in Uri

### ISSUE THREAD

**Issue by zbstof** [phrawzty/check_http_json#25]
When calling script with uri parameter which does not contain protocol, e.g. 
`./check_http_json.rb -v -u 'node.office.de:9200/_cluster/health' -e number_of_data_nodes -c 2:2 -w 2:2`
there's an error displayed:
`+ Exception occured: undefined method 'request_uri' for #<URI::Generic:0x7fe0b41e5770>.`
`UNKNOWN: HTTP connection failed.`
My guess would be that request_uri is not present if protocol is absent, so we can not start timeout request.

**Comment by phrawzty** [comment]
You are correct - the protocol must be supplied for the URI to be valid (which is the source of the error).  The solution is to add the URI, for example, `http://`.

Anything else I can help with?

**Comment by zbstof** [comment]
Maybe it should assume http if it doesn't know better? It would be reasonable default. Right now I have to hard-code this into my application.

**Comment by phrawzty** [comment]
Sadly, the `URI` library isn't magic - it expects a properly-formed URI and it doesn't do much in the way or error checking.  I could parse the URI string manually beforehand and check to see it it starts with `http[s]` (and if not, prefix with `http://`), but it's a bit of a hack.  Furthermore, this would have unintended consequences if the malformed URI just happens to start with `http`, as in `./check_http_json.rb -u 'http-server.domain.ext/this/that/'.

Ultimately, I don't feel that a properly-formed URI is an unreasonable expectation, and I'm hesitant to alter expected behaviour.  That said, [here's a branch](https://github.com/phrawzty/check_http_json/tree/http_by_default) that does what you want (be warned that I won't maintain it, however).
