### ISSUE TITLE
Escape or remove pipes in plugin output

### ISSUE THREAD

**Issue by ggzengel** [phrawzty/check_http_json#42]
On using pipes (|) in regex the performance label will have wrong names:

```
# /srv/icinga/linux/check_http_json.rb -u http://heizung:4321/xyz1/all -e pe1.L_state -R "^(1|2|3|4|5|99)$" --perf "pe1.L_usb_stick" 
OK: 'pe1.L_state' (regex) does match ^(1|2|3|4|5|99)$ | system.L_usb_stick=0
```

![image](https://user-images.githubusercontent.com/12020614/50098071-84638d00-021b-11e9-9ea1-c6cfa71bcf8d.png)

**Comment by phrawzty** [comment]
Hello. Thanks for your patience - I'm back from vacation. 🙂 

Your issue, if I understand it correctly, is not with the output of the script itself, but rather with how that output is rendered within Nagios itself. This is a fair criticism, but to be honest, I'm not comfortable with arbitrarily altering the source output in order to deal with a bug that exists elsewhere. If your solution works for you - great! But I'm not going to push that behaviour on to anybody else.

Another alternative would be to pipe it through `cut` or something, I suppose.

```json
{
   "Test": "3",
   "Blah1": "0"
}
```

```
$ ./check_http_json.rb -f x.json -e Test -R "^(0|3|99)$" --perf Blah1
OK: 'Test' (regex) does match ^(0|3|99)$ | Blah1=0
$ ./check_http_json.rb -f x.json -e Test -R "^(0|3|99)$" --perf Blah1 | cut -d '|' -f 4
 Blah1=0
```

**Comment by ggzengel** [comment]
No, it's not a problem of Nagios or Icinga.
It a problem that the program repeats the input (here the regex) which has not allow chars because pipes are the delimiters.
The text before and after the (one and only) pipe has it's meaning.
So there should be exactly one pipe in this output. Not more not less.

**Comment by MarcusCaepio** [comment]
Hey all,
late to the party, but I can confirm @ggzengel 
The pipe is a reserved char which signals the monitoring program, that performance data is coming. This is part of the nagios plugins developement guide and is valid for also the monitoring-plugins project, nagios, icinga2 and so on.
See https://nagios-plugins.org/doc/guidelines.html#AEN200

**Comment by phrawzty** [comment]
Ah, OK, I understand. It only took like six years, but sure, I'll update this thing. 😆

**Comment by phrawzty** [comment]
Given `test.json` that contains a pipe:
```json
{
    "this" : "that|other"
}
```

Pipes in the output are now bangs by default.
```
$ ./check_http_json.rb -f test.json -e this -r "that|other"
OK: this does match 'that!other'
```

If you want a different character, use `--output_alt_pipe`:
```
$ ./check_http_json.rb -f test.json -e this -r "that|other" --output_alt_pipe "π"
OK: this does match 'thatπother'
```

**If you don't want output substitutions to occur, specify a pipe as the alt character**:
```
$ ./check_http_json.rb -f ~/test.json -e this -r "that|other" --output_alt_pipe "|"
OK: this does match 'that|other'
```

Why? Because pipes are ✨sacred✨ symbols in Nagios output, and this behaviour should have been default in the first place. Late is better than never, right?
